name: $(Build.BuildId)

trigger:
  - master

parameters:
  - name: image
    displayName: Pool Image
    type: string
    default: ubuntu-latest
    values:
      - windows-latest
      - vs2017-win2016
      - ubuntu-latest
      - ubuntu-16.04
      - macOS-latest
      - macOS-10.14

steps:
- template: initialise-iac.yml  