name: $(Build.BuildId)

trigger:
  - master

resources:
  repositories:
    - repository: Libraries
      type: git
      name: YAMLPOCTemplates/Libraries


parameters:
  - name: image    
    displayName: Pool Image
    type: string
    default: ubuntu-latest
    values:
      - windows-latest
      - vs2017-win2016
      - ubuntu-latest
      - ubuntu-16.04
      - macOS-latest
      - macOS-10.14


stages:
  # Initialise stages
  - stage: FirstStage
    jobs:
    - template: initialise-iac.yml
      parameters:
        poolimage: ${{ parameters.image }}  
  - stage: SecondStage
    jobs:
    - template: initialise-iac.yml
      parameters:
        poolimage: ${{ parameters.image }}  